### ISSUE TITLE
MLM - Rockfalls

### ISSUE THREAD

**Issue by Elli-tt** [ItsCuell/walker#13]
# Rockfalls

There are two rockfalls which block a player from entering the bank/deposit Hopper in MLM from the Dwarven Mine entrance.

They do not act as a shortcut due to the player not being force moved when they are interacted with.

![image](https://github.com/ItsCuell/walker/assets/18116850/780da307-b3c3-4453-99d5-32c02b00a70a)
![image](https://github.com/ItsCuell/walker/assets/18116850/6dc8107c-b1dd-44a7-9d38-90d74f2231ac)

**Comment by ItsCuell** [comment]
Should now be fixed
